arch:
  - amd64
  - ppc64le

dist: trusty

addons:
  apt:
    packages:
      - maven

language: java

jdk:
  - openjdk7
  - openjdk8
  - openjdk11
#  - openjdk12 add once code is requires Java 7


# No need for preliminary install step.
install: true
#
# Run all integration tests.
script: 
  - "mvn --show-version --errors --batch-mode clean verify"
#
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - khmarbaise@apache.org
